### ISSUE TITLE
A couple of typos in the first use case

### ISSUE THREAD

**Issue by robsemmens** [giocomai/zoteroR#1]
Thanks so much for creating this!  Worked great, but I stumbled into some typos:

library("zoteror")  ## I don't think you want quotes here

big_collection_id <- zot_create_collection(collectionName = "plus5") #creates collection "plus5", and if already existing simply outputs its key

#the documentation shows collection_name, not collectionName

for (i in seq_along(bigIDs$ID)) {
    try(zot_add_to_collection(id = bigIDs$ID[i], collectionId = big_collection_id))
}

#the documentation shows collection_id, not collectionId

Super minor stuff, for sure, but it might trip up users who don't have a lot of troubleshooting in R.  Thanks again!

**Comment by giocomai** [comment]
Indeed, I switched to snake_case earlier on in all functions but forgot to update the readme, which unfortunately remained in camelCase. 

Thanks for raising this issue! Fixed all things you mentioned, and some more. 

Oh, I actually like my quotes in library calls. This is rarely an issue, but is not without reason, see e.g. http://adv-r.had.co.nz/Computing-on-the-language.html#nse-downsides

**Comment by robsemmens** [comment]
Thanks for the link!  I did not know NSE was even a thing.
